import type { StepRecord } from "../orchestrator/types.js";
import type { Provenance } from "../hands/types.js";

export type GateProvenance = Provenance | "unknown";

export interface GateItem {
  field: string;
  value: string;
  /** Needed so an edit at the gate can re-fill this exact element (§9.5). */
  ref: string;
}

export interface GateGroup {
  provenance: GateProvenance;
  label: string;
  items: GateItem[];
  expanded: boolean;
}

export interface GateView {
  groups: GateGroup[];
  /** Every filled field. */
  total: number;
  /** The ones a human actually has to read. */
  needsReview: number;
}

const LABEL: Record<GateProvenance, string> = {
  generated: "⚠ Generated by Clippy",
  unknown: "⚠ Source unknown",
  human: "✓ Written by you",
  profile: "✓ Copied from your profile",
};

/** Riskiest first. A dialog is read top-down, so ordering IS the emphasis. */
const ORDER: GateProvenance[] = ["generated", "unknown", "human", "profile"];

/**
 * Group the fills for the Submit gate by provenance (spec §9.5).
 *
 * Only `generated` and `unknown` are expanded. Values copied verbatim from the
 * profile collapse to a single line with a count, because reading sixteen
 * correct rows to find two risky ones is how a gate stops being read at all.
 */
export function buildGateView(steps: StepRecord[]): GateView {
  const buckets = new Map<GateProvenance, GateItem[]>();

  for (const step of steps) {
    const a = step.action;
    if (a.kind !== "fill" && a.kind !== "select") continue;
    // Absent provenance is `unknown`, never `profile`. An unmarked value has not
    // been shown to come from anywhere trustworthy.
    const p: GateProvenance = a.provenance ?? "unknown";
    const list = buckets.get(p) ?? [];
    list.push({ field: step.effect, value: a.value, ref: a.ref });
    buckets.set(p, list);
  }

  const groups: GateGroup[] = ORDER.filter((p) => buckets.has(p)).map((p) => ({
    provenance: p,
    label: LABEL[p],
    items: buckets.get(p)!,
    expanded: p === "generated" || p === "unknown",
  }));

  const total = [...buckets.values()].reduce((n, l) => n + l.length, 0);
  const needsReview = groups.filter((g) => g.expanded).reduce((n, g) => n + g.items.length, 0);
  return { groups, total, needsReview };
}
